### PR TITLE
Reuse ArrayEnumerable.Concat in Result.CombineEmpty

### PR DESCRIPTION
**Pull request by atifaziz**
Rationale: less is more

### CODE REVIEW

**Comment by nblumhardt** [comment]
Thanks!

**Comment by atifaziz** [comment]
Is there anything keeping this from being merged?

**Comment by nblumhardt** [comment]
Hi Atif - sorry about the delay. It's just a matter of available time for reviews right now, I'm on vacation and have a bit of a backlog of PRs etc. to get through as soon as I'm back online in the New Year, when hopefully everything will be back to running smoothly 😅 - Thanks!

**Comment by atifaziz** [comment]
@nblumhardt Hey, no worries. Enjoy your holidays.

**Comment by nblumhardt** [comment]
Thanks again for the PR!

(Holiday was great, thanks! :-))

**Pull request merged**
