### PR TITLE
Initial api suggestion to add TextSpan.ConsumeRegex

### PR DESCRIPTION
**Pull request by xtofs**
Hello Nicholas,
 
I saw a discussion about Keyword Tokens and suggest to have something like
`current.ConsumeRegex("if|then|else");` in the tokenizer. 
Under the cover it uses an anchored regular expression and advances the text span multiple characters at ones.

The pull request has a minimal implementation with little test coverage. I understand it would need more tests including some performance test. I would love to finish that, but wanted to get that in front of you, and hear what you generally think about the idea to mix the Regex paradigm into the tokenizer.

Christof

### CODE REVIEW

**Comment by nblumhardt** [comment]
Thanks for the suggestion and PR. Taking a few days off, but keen to check this out soon 👍

**Comment by nblumhardt** [comment]
Back! Sorry about the delay, Christof.

The Superpower tokenizers can use `TextParser`s as matchers; I wonder if we could incorporate an API more like `Span.Matching(regex)`?

This'd be used in much the same way as the `Numerics.Integer()` parser is used in: https://github.com/datalust/superpower/blob/dev/sample/IntCalc/ArithmeticExpressionTokenizer.cs#L32, or the `FilterExpressionTextParsers.SqlString()` parser used in: https://github.com/serilog/serilog-filters-expressions/blob/dev/src/Serilog.Filters.Expressions/Filters/Expressions/Parsing/FilterExpressionTokenizer.cs#L98.

Thoughts?

Best regards,
Nick

**Comment by xtofs** [comment]
Give me a day or two to look into it. But my first gut feeling is yes. The place where I put it didn’t feel 100% right. I have not used superpower a lot and I need to get more comfortable with the disctintion between text- and token parser.

**Comment by nblumhardt** [comment]
Hi @xtofs - I've added a `Span.Regex()` parser in #25 - would be great if you can check it out, once it's all merged and pushed to `dev`! Thanks for the input on this 👍

**Comment by xtofs** [comment]
Thanks Nicholas,

that looks great. Sorry for not actually contributing something in time.

Christof

**Comment by xtofs** [comment]
Nicholas,

Just saw that the RegexOpions parameter is not used and the parser fails if it relies on it. I plan to send a small pull request.

From: Christof Sprenger <christof_sprenger@hotmail.com>
Date: Sunday, February 18, 2018 at 10:17
To: datalust/superpower <reply@reply.github.com>
Subject: Re: [datalust/superpower] Initial api suggestion to add TextSpan.ConsumeRegex (#22)

Thanks Nicholas,

that looks great. Sorry for not actually contributing something in time.

Christof

**Comment by nblumhardt** [comment]
Nice catch! Thanks, @xtofs 👍

**Pull request closed without merging**
